apiVersion: v1
kind: Namespace
metadata:
  name: ${CABPR_NAMESPACE}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster 
metadata:
  namespace: ${CABPR_NAMESPACE}
  name: ${CABPR_CLUSTER_NAME} 
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
    kind: RKE2ControlPlane
    name: ${CABPR_CLUSTER_NAME}-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: ${CABPR_CLUSTER_NAME}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  name: ${CABPR_CLUSTER_NAME}
  namespace: ${CABPR_NAMESPACE}
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: RKE2ControlPlane
metadata:
  name: ${CABPR_CLUSTER_NAME}-control-plane
  namespace: ${CABPR_NAMESPACE}
spec: 
  replicas: ${CABPR_CP_REPLICAS}
  version: ${KUBERNETES_VERSION}+rke2r1
  airGapped: true
  serverConfig:
    cni: cilium
  kubeProxy:
    extraEnv:
      hello: world
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerMachineTemplate
    name: controlplane
  nodeDrainTimeout: 2m
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: controlplane
  namespace: ${CABPR_NAMESPACE}
spec:
  template:
    spec: 
      customImage: rke2-ubuntu:${KUBERNETES_VERSION}-rke2r1
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: worker-md-0
  namespace: ${CABPR_NAMESPACE}
spec:
  clusterName: ${CABPR_CLUSTER_NAME}
  replicas: ${CABPR_WK_REPLICAS}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: ${CABPR_CLUSTER_NAME}
  template:
    spec:
      version: ${KUBERNETES_VERSION}
      clusterName: ${CABPR_CLUSTER_NAME}
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
          kind: RKE2ConfigTemplate
          name: ${CABPR_CLUSTER_NAME}-agent
          namespace: ${CABPR_NAMESPACE}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: worker
        namespace: ${CABPR_NAMESPACE}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: worker
  namespace: ${CABPR_NAMESPACE}
spec:
  template:
    spec: 
      customImage: rke2-ubuntu:${KUBERNETES_VERSION}-rke2r1
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
kind: RKE2ConfigTemplate
metadata:
  namespace: ${CABPR_NAMESPACE}
  name: ${CABPR_CLUSTER_NAME}-agent
spec: 
  template:
    spec:
      agentConfig:
        version: ${KUBERNETES_VERSION}+rke2r1
        airGapped: true
        kubeProxy:
          extraEnv:
            hello: world
