---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ${CABPR_NAMESPACE}
  name: worker-md-0
  namespace: ${CABPR_NAMESPACE}
spec:
  clusterName: ${CABPR_CLUSTER_NAME}
  replicas: ${CABPR_WK_REPLICAS}
  selector:
    matchLabels: {}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: ${CABPR_CLUSTER_NAME}
    spec:
      version: ${KUBERNETES_VERSION}
      clusterName: ${CABPR_CLUSTER_NAME}
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
          kind: RKE2ConfigTemplate
          name: rke2-agent
          namespace: ${CABPR_NAMESPACE}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: VSphereMachineTemplate
        name: vsphere-worker
        namespace: ${CABPR_NAMESPACE}


